name = "directus-marketplace-search-mcp"
main = "dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./dist/index.js"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[vars]
ENVIRONMENT = "development"

# Add secrets using: wrangler secret put SECRET_NAME
# Example secrets to configure:
# - DIRECTUS_API_TOKEN (if needed for private marketplace)
# - ANALYTICS_TOKEN (for monitoring)

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }