name = "directus-marketplace-search-mcp"
main = "dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "CACHE"
id = "45941015c56f4889a9b797948b1559ca"

[vars]
ENVIRONMENT = "development"

# Add secrets using: wrangler secret put SECRET_NAME
# Example secrets to configure:
# - DIRECTUS_API_TOKEN (if needed for private marketplace)
# - ANALYTICS_TOKEN (for monitoring)

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }